config/routes.rb
Rails.application.routes.draw do
  resources :koko_test_ajas
  resources :questions
  resources :users
  resources :badges
  resources :questionsets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/koko_test_aja.rb
class KokoTestAja < ApplicationRecord
end

app/controllers/koko_test_ajas_controller.rb
class KokoTestAjasController < ApplicationController
  before_action :set_koko_test_aja, only: [:show, :edit, :update, :destroy]

  # GET /koko_test_ajas
  # GET /koko_test_ajas.json
  def index
    @koko_test_ajas = KokoTestAja.all
  end

  # GET /koko_test_ajas/1
  # GET /koko_test_ajas/1.json
  def show
  end

  # GET /koko_test_ajas/new
  def new
    @koko_test_aja = KokoTestAja.new
  end

  # GET /koko_test_ajas/1/edit
  def edit
  end

  # POST /koko_test_ajas
  # POST /koko_test_ajas.json
  def create
    @koko_test_aja = KokoTestAja.new(koko_test_aja_params)

    respond_to do |format|
      if @koko_test_aja.save
        format.html { redirect_to @koko_test_aja, notice: 'Koko test aja was successfully created.' }
        format.json { render :show, status: :created, location: @koko_test_aja }
      else
        format.html { render :new }
        format.json { render json: @koko_test_aja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /koko_test_ajas/1
  # PATCH/PUT /koko_test_ajas/1.json
  def update
    respond_to do |format|
      if @koko_test_aja.update(koko_test_aja_params)
        format.html { redirect_to @koko_test_aja, notice: 'Koko test aja was successfully updated.' }
        format.json { render :show, status: :ok, location: @koko_test_aja }
      else
        format.html { render :edit }
        format.json { render json: @koko_test_aja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /koko_test_ajas/1
  # DELETE /koko_test_ajas/1.json
  def destroy
    @koko_test_aja.destroy
    respond_to do |format|
      format.html { redirect_to koko_test_ajas_url, notice: 'Koko test aja was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koko_test_aja
      @koko_test_aja = KokoTestAja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def koko_test_aja_params
      params.require(:koko_test_aja).permit(:name, :age)
    end
end

app/helpers/koko_test_ajas_helper.rb
module KokoTestAjasHelper
end

app/views/koko_test_ajas/_form.html.erb
<%= form_for(koko_test_aja) do |f| %>
  <% if koko_test_aja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(koko_test_aja.errors.count, "error") %> prohibited this koko_test_aja from being saved:</h2>

      <ul>
      <% koko_test_aja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/koko_test_ajas/edit.html.erb
<h1>Editing Koko Test Aja</h1>

<%= render 'form', koko_test_aja: @koko_test_aja %>

<%= link_to 'Show', @koko_test_aja %> |
<%= link_to 'Back', koko_test_ajas_path %>

app/views/koko_test_ajas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Koko Test Ajas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @koko_test_ajas.each do |koko_test_aja| %>
      <tr>
        <td><%= koko_test_aja.name %></td>
        <td><%= koko_test_aja.age %></td>
        <td><%= link_to 'Show', koko_test_aja %></td>
        <td><%= link_to 'Edit', edit_koko_test_aja_path(koko_test_aja) %></td>
        <td><%= link_to 'Destroy', koko_test_aja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Koko Test Aja', new_koko_test_aja_path %>

app/views/koko_test_ajas/new.html.erb
<h1>New Koko Test Aja</h1>

<%= render 'form', koko_test_aja: @koko_test_aja %>

<%= link_to 'Back', koko_test_ajas_path %>

app/views/koko_test_ajas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @koko_test_aja.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @koko_test_aja.age %>
</p>

<%= link_to 'Edit', edit_koko_test_aja_path(@koko_test_aja) %> |
<%= link_to 'Back', koko_test_ajas_path %>